#!/usr/bin/env bats

setup() {
    load ../import_showtime.bash
}

@test "./show" {
    run ./show
    [ "$status" -eq 1 ]
    [[ "${lines[0]}" = "Usage"* ]]
}

@test "./show --help" {
    run ./show --help
    [ "$status" -eq 1 ]
    [[ "${lines[0]}" = "Usage"* ]]
}

@test "./show --clean only" {
    run ./show --clean
    [ "$status" -eq 1 ]
    [[ "${lines[0]}" = *"Please"* ]]
}

@test "./show --clean --offline" {
    run ./show --clean --offline
    [ "$status" -eq 1 ]
    [[ "${lines[0]}" = "ERR: CLEAN and OFFLINE can't be set together"* ]]
}

@test "./show --clean not found" {
    run ./show --clean test/run/demo
    [ "$status" -eq 1 ]
    [[ "${lines[0]}" = "WRN: Clean script"* ]]
}

@test "./show --offline not found" {
    run ./show --offline test/run/demo
    [ "$status" -eq 1 ]
    [[ "${lines[0]}" = "WRN: Offline script"* ]]
}

@test "./show full" {
    run ./show test/run/full
    [ "$status" -eq 0 ]
    [[ "${lines[0]}" = *"demo"* ]]
}

@test "./show --clean foo" {
    run ./show --clean test/run/full
    [ "$status" -eq 0 ]
    [[ "${lines[0]}" = *"clean"* ]]
}

@test "./show --offline foo" {
    run ./show --offline test/run/full
    [ "$status" -eq 0 ]
    [[ "${lines[0]}" = *"offline"* ]]
}

@test "./show theme" {
    run ./show test/run/theme
    [ "$status" -eq 0 ]
    [[ "${lines[0]}" = *">"*"demo"* ]]
}

@test "./show --export sh" {
    run ./show --export sh test/run/full
    [ "$status" -eq 0 ]
    [ "$status" = 0 ]
    [[ "${lines[0]}" = "#!/bin/bash" ]]
    [[ "${lines[1]}" = "# Generated by showtime" ]]
    [[ "${lines[2]}" = "# demo" ]]
    [[ "${lines[3]}" = "echo \"test\"" ]]
}

@test "./show --export md" {
    run ./show --export md test/run/full
    [ "$status" -eq 0 ]
    [[ "${lines[0]}" = "demo" ]]
    [[ "${lines[1]}" = "\`\`\`bash" ]]
    [[ "${lines[2]}" = "echo \"test\"" ]]
    [[ "${lines[3]}" = "\`\`\`" ]]
}

@test "./show --export md --clean" {
    run ./show --export md --clean test/run/full
    [ "$status" -eq 0 ]
    [[ "${lines[0]}" = "clean" ]]
}

@test "./show --export md --offline" {
    run ./show --export md --offline test/run/full
    [ "$status" -eq 0 ]
    [[ "${lines[0]}" = "offline" ]]
}