#! /usr/bin/env bats

setup() {
    load ../test_helper/bats-support/load
    load ../test_helper/bats-assert/load
    load ../import_showtime.bash
}


@test "_export_intestation" {
    run _export_intestation
    assert_failure
    assert_output ""
}

@test "EXPORT_FORMAT='sh' _export_intestation" {
    EXPORT_FORMAT='sh' run _export_intestation
    assert_success
    assert_output --partial "#!/bin/bash"
    assert_output --partial "# Generated by showtime"
}

@test "EXPORT_FORMAT='md' _export_intestation" {
    EXPORT_FORMAT='md' run _export_intestation
    assert_success
    assert_output ""
}

@test "_export_sh_intestation" {
    run _export_sh_intestation
    assert_success
    assert_output --partial "#!/bin/bash"
    assert_output --partial "# Generated by showtime"
}
