#! /usr/bin/env bats

load ../import_showtime.bash

@test "_export_intestation" {
    run _export_intestation
    (( status == 0 ))
    [[ "${lines[0]}" = "" ]]
}

@test "EXPORT=true _export_intestation" {
    EXPORT=true run _export_intestation
    (( status == 0 ))
    [[ "${lines[0]}" = "#!/bin/bash" ]]
    [[ "${lines[1]}" = "# Generated by showtime" ]]
}

@test "EXPORT_FORMAT=sh _export_intestation" {
    EXPORT_FORMAT=sh run _export_intestation
    (( status == 0 ))
    [[ "${lines[0]}" = "#!/bin/bash" ]]
    [[ "${lines[1]}" = "# Generated by showtime" ]]
}

@test "EXPORT_FORMAT=md _export_intestation" {
    EXPORT_FORMAT=md run _export_intestation
    (( status == 0 ))
    [[ "${lines[0]}" = "" ]]
}

@test "_export_sh_intestation" {
    run _export_sh_intestation
    (( status == 0 ))
    [[ "${lines[0]}" = "#!/bin/bash" ]]
    [[ "${lines[1]}" = "# Generated by showtime" ]]
}